version: 2.1.0.{build}

platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
# branches to build
branches:
  # whitelist
  only:
  - master
  - develop

on_finish:
  - ps: $blockRdp = $true; Invoke-Expression (Invoke-WebRequest 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')


# clone directory
clone_folder: c:\projects\liblogicalaccess
install:
#  - cmd: sed -i '/version = "2.1.0"/c\    version = "%APPVEYOR_BUILD_VERSION%"' conanfile.py
  - cmd: cat conanfile.py
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

before_build:
  - cmd: cd c:\projects\liblogicalaccess

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan create .. LogicalAccess/2.1.0.35@islog/%APPVEYOR_REPO_BRANCH%
  - cmd: conan install .. -o LLA_BUILD_UNITTEST=True --build gtest
  - cmd: conan build ..

test_script:
  - cmd: ctest -C Release
